### ISSUE TITLE
Git Conflict Markers showing up in website since v0.0.48 release

### ISSUE THREAD

**Issue by rohanKanojia** [jkubeio/jkube-website#59]
I'm observing this after Release [0.0.48](https://github.com/jkubeio/jkube-website/releases/tag/v0.0.48) 

I was checking the result of my deployed changes but noticed something strange.

Not sure if it's just me but I'm seeing Git Conflict Markers on our landing page.  The title also doesn't seem to be updated:
![Screenshot from 2023-01-21 00-27-11](https://user-images.githubusercontent.com/13834498/213782782-57159799-76e0-4c07-9704-c4798c03a159.png)

**Comment by rohanKanojia** [comment]
I'm not able to see the same thing when deploying the website locally. Could there be some unresolved conflict left on the server where it's being deployed?

**Comment by manusa** [comment]
Hi, just seeing this issue.
Yes, I noticed when the page was updated.
My guess is that it has to do with the Eclipse script since the target repository https://github.com/jkubeio/jkube-website-publish doesn't contain those markers.

I opened the following issue at Eclipse's Gitlab: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2543

**Comment by manusa** [comment]
We still need to change the script

**Comment by manusa** [comment]
Fixed by:
- https://github.com/jkubeio/jkube-website/commit/601505500426cd9a8a33ee48fabd011653ead45f
- https://github.com/jkubeio/jkube-website/commit/36cf20ee13618746a5e64853f28a7feb9de53757
